ARG DENO_VERSION=1.42.3

# Stage 1: Install Deno
FROM denoland/deno:$DENO_VERSION
RUN deno --version



# Fügen Sie den Deno-Pfad zur Umgebungsvariable hinzu
ENV DENO_INSTALL="/usr/local/bin/deno"

# Führen Sie den Befehl aus, um die Typdefinitionen für Deno zu installieren
# RUN deno install -g --allow-read --allow-write https://deno.land/x/deno_types/gen.d.ts

# Setzen Sie den Pfad für Deno in der Umgebungsvariable
ENV PATH=$DENO_INSTALL:$PATH

# Setzen Sie das Arbeitsverzeichnis für Ihre App
WORKDIR /app

# Kopieren Sie Ihre Anwendungsdateien in das Arbeitsverzeichnis
COPY src ./
COPY content .

RUN deno cache main.ts

RUN mkdir outputData

ENTRYPOINT ["deno", "run", "--allow-net", "--allow-read", "--allow-write", "main.ts", "progress/topics/c6906727-fbd8-419a-809e-4a24de352d0d/trainings/26408628-a743-4f28-9d36-e4f7b4bcf636/questionnaires/4ec93c9d-53ac-4769-9ec0-d1c7220ed0c7/questions", "./basisschulungen/dokumentation.json"]